// Code generated by goctl. DO NOT EDIT.
package types

type IpReq struct {
	Ip string `path:"name"`
}

type PhoneReq struct {
	Phone string `path:"name"`
}

type CommonResp struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg,omitempty"`
	Data interface{} `json:"data,omitempty"`
}
