// Code generated by protoc-gen-go. DO NOT EDIT.
// source: phoneloc.proto

package phoneloc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PhoneLocReq struct {
	Phone                string   `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PhoneLocReq) Reset()         { *m = PhoneLocReq{} }
func (m *PhoneLocReq) String() string { return proto.CompactTextString(m) }
func (*PhoneLocReq) ProtoMessage()    {}
func (*PhoneLocReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd7e7899d2af1754, []int{0}
}

func (m *PhoneLocReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PhoneLocReq.Unmarshal(m, b)
}
func (m *PhoneLocReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PhoneLocReq.Marshal(b, m, deterministic)
}
func (m *PhoneLocReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PhoneLocReq.Merge(m, src)
}
func (m *PhoneLocReq) XXX_Size() int {
	return xxx_messageInfo_PhoneLocReq.Size(m)
}
func (m *PhoneLocReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PhoneLocReq.DiscardUnknown(m)
}

var xxx_messageInfo_PhoneLocReq proto.InternalMessageInfo

func (m *PhoneLocReq) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type PhoneLocResp struct {
	Prov                 string   `protobuf:"bytes,1,opt,name=prov,proto3" json:"prov,omitempty"`
	ProvCode             int32    `protobuf:"varint,2,opt,name=prov_code,json=provCode,proto3" json:"prov_code,omitempty"`
	City                 string   `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	CityCode             int32    `protobuf:"varint,4,opt,name=city_code,json=cityCode,proto3" json:"city_code,omitempty"`
	Isp                  string   `protobuf:"bytes,5,opt,name=isp,proto3" json:"isp,omitempty"`
	Postcode             string   `protobuf:"bytes,6,opt,name=postcode,proto3" json:"postcode,omitempty"`
	Tel                  string   `protobuf:"bytes,7,opt,name=tel,proto3" json:"tel,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PhoneLocResp) Reset()         { *m = PhoneLocResp{} }
func (m *PhoneLocResp) String() string { return proto.CompactTextString(m) }
func (*PhoneLocResp) ProtoMessage()    {}
func (*PhoneLocResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd7e7899d2af1754, []int{1}
}

func (m *PhoneLocResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PhoneLocResp.Unmarshal(m, b)
}
func (m *PhoneLocResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PhoneLocResp.Marshal(b, m, deterministic)
}
func (m *PhoneLocResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PhoneLocResp.Merge(m, src)
}
func (m *PhoneLocResp) XXX_Size() int {
	return xxx_messageInfo_PhoneLocResp.Size(m)
}
func (m *PhoneLocResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PhoneLocResp.DiscardUnknown(m)
}

var xxx_messageInfo_PhoneLocResp proto.InternalMessageInfo

func (m *PhoneLocResp) GetProv() string {
	if m != nil {
		return m.Prov
	}
	return ""
}

func (m *PhoneLocResp) GetProvCode() int32 {
	if m != nil {
		return m.ProvCode
	}
	return 0
}

func (m *PhoneLocResp) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *PhoneLocResp) GetCityCode() int32 {
	if m != nil {
		return m.CityCode
	}
	return 0
}

func (m *PhoneLocResp) GetIsp() string {
	if m != nil {
		return m.Isp
	}
	return ""
}

func (m *PhoneLocResp) GetPostcode() string {
	if m != nil {
		return m.Postcode
	}
	return ""
}

func (m *PhoneLocResp) GetTel() string {
	if m != nil {
		return m.Tel
	}
	return ""
}

func init() {
	proto.RegisterType((*PhoneLocReq)(nil), "phoneloc.PhoneLocReq")
	proto.RegisterType((*PhoneLocResp)(nil), "phoneloc.PhoneLocResp")
}

func init() { proto.RegisterFile("phoneloc.proto", fileDescriptor_dd7e7899d2af1754) }

var fileDescriptor_dd7e7899d2af1754 = []byte{
	// 213 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0xc8, 0xc8, 0xcf,
	0x4b, 0xcd, 0xc9, 0x4f, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x80, 0xf1, 0x95, 0x94,
	0xb9, 0xb8, 0x03, 0x40, 0x6c, 0x9f, 0xfc, 0xe4, 0xa0, 0xd4, 0x42, 0x21, 0x11, 0x2e, 0x56, 0xb0,
	0x94, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x84, 0xa3, 0xb4, 0x81, 0x91, 0x8b, 0x07, 0xa1,
	0xaa, 0xb8, 0x40, 0x48, 0x88, 0x8b, 0xa5, 0xa0, 0x28, 0xbf, 0x0c, 0xaa, 0x0a, 0xcc, 0x16, 0x92,
	0xe6, 0xe2, 0x04, 0xd1, 0xf1, 0xc9, 0xf9, 0x29, 0xa9, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0xac, 0x41,
	0x1c, 0x20, 0x01, 0xe7, 0xfc, 0x94, 0x54, 0x90, 0x86, 0xe4, 0xcc, 0x92, 0x4a, 0x09, 0x66, 0x88,
	0x06, 0x10, 0x1b, 0xa4, 0x01, 0x44, 0x43, 0x34, 0xb0, 0x40, 0x34, 0x80, 0x04, 0xc0, 0x1a, 0x04,
	0xb8, 0x98, 0x33, 0x8b, 0x0b, 0x24, 0x58, 0xc1, 0xea, 0x41, 0x4c, 0x21, 0x29, 0x2e, 0x8e, 0x82,
	0xfc, 0xe2, 0x12, 0xb0, 0x6a, 0x36, 0xb0, 0x30, 0x9c, 0x0f, 0x52, 0x5d, 0x92, 0x9a, 0x23, 0xc1,
	0x0e, 0x51, 0x5d, 0x92, 0x9a, 0x63, 0xe4, 0xc8, 0xc5, 0x01, 0x73, 0xb1, 0x90, 0x29, 0x17, 0x8b,
	0x5b, 0x66, 0x5e, 0x8a, 0x90, 0xa8, 0x1e, 0x3c, 0x18, 0x90, 0xfc, 0x2c, 0x25, 0x86, 0x4d, 0xb8,
	0xb8, 0x20, 0x89, 0x0d, 0x1c, 0x56, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x11, 0x5d, 0xdb,
	0x75, 0x3d, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PhoneLocClient is the client API for PhoneLoc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PhoneLocClient interface {
	Find(ctx context.Context, in *PhoneLocReq, opts ...grpc.CallOption) (*PhoneLocResp, error)
}

type phoneLocClient struct {
	cc *grpc.ClientConn
}

func NewPhoneLocClient(cc *grpc.ClientConn) PhoneLocClient {
	return &phoneLocClient{cc}
}

func (c *phoneLocClient) Find(ctx context.Context, in *PhoneLocReq, opts ...grpc.CallOption) (*PhoneLocResp, error) {
	out := new(PhoneLocResp)
	err := c.cc.Invoke(ctx, "/phoneloc.PhoneLoc/Find", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PhoneLocServer is the server API for PhoneLoc service.
type PhoneLocServer interface {
	Find(context.Context, *PhoneLocReq) (*PhoneLocResp, error)
}

// UnimplementedPhoneLocServer can be embedded to have forward compatible implementations.
type UnimplementedPhoneLocServer struct {
}

func (*UnimplementedPhoneLocServer) Find(ctx context.Context, req *PhoneLocReq) (*PhoneLocResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Find not implemented")
}

func RegisterPhoneLocServer(s *grpc.Server, srv PhoneLocServer) {
	s.RegisterService(&_PhoneLoc_serviceDesc, srv)
}

func _PhoneLoc_Find_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PhoneLocReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhoneLocServer).Find(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/phoneloc.PhoneLoc/Find",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhoneLocServer).Find(ctx, req.(*PhoneLocReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _PhoneLoc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "phoneloc.PhoneLoc",
	HandlerType: (*PhoneLocServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Find",
			Handler:    _PhoneLoc_Find_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "phoneloc.proto",
}
