// Code generated by goctl. DO NOT EDIT!
// Source: iploc.proto

package server

import (
	"context"

	"demo/app/services/iploc/internal/logic"
	"demo/app/services/iploc/internal/svc"
	"demo/app/services/iploc/iploc"
)

type IpLocServer struct {
	svcCtx *svc.ServiceContext
}

func NewIpLocServer(svcCtx *svc.ServiceContext) *IpLocServer {
	return &IpLocServer{
		svcCtx: svcCtx,
	}
}

func (s *IpLocServer) Find(ctx context.Context, in *iploc.IpAddr) (*iploc.IpResult, error) {
	l := logic.NewFindLogic(ctx, s.svcCtx)
	return l.Find(in)
}
