// Code generated by goctl. DO NOT EDIT!
// Source: phoneloc.proto

package server

import (
	"context"

	"demo/app/services/phoneloc/internal/logic"
	"demo/app/services/phoneloc/internal/svc"
	"demo/app/services/phoneloc/phoneloc"
)

type PhoneLocServer struct {
	svcCtx *svc.ServiceContext
}

func NewPhoneLocServer(svcCtx *svc.ServiceContext) *PhoneLocServer {
	return &PhoneLocServer{
		svcCtx: svcCtx,
	}
}

func (s *PhoneLocServer) Find(ctx context.Context, in *phoneloc.PhoneLocReq) (*phoneloc.PhoneLocResp, error) {
	l := logic.NewFindLogic(ctx, s.svcCtx)
	return l.Find(in)
}
