// Code generated by goctl. DO NOT EDIT!
// Source: phoneloc.proto

//go:generate mockgen -destination ./phoneloc_mock.go -package phonelocclient -source $GOFILE

package phonelocclient

import (
	"context"

	"demo/app/services/phoneloc/phoneloc"

	"github.com/zeromicro/go-zero/zrpc"
)

type (
	PhoneLocReq  = phoneloc.PhoneLocReq
	PhoneLocResp = phoneloc.PhoneLocResp

	PhoneLoc interface {
		Find(ctx context.Context, in *PhoneLocReq) (*PhoneLocResp, error)
	}

	defaultPhoneLoc struct {
		cli zrpc.Client
	}
)

func NewPhoneLoc(cli zrpc.Client) PhoneLoc {
	return &defaultPhoneLoc{
		cli: cli,
	}
}

func (m *defaultPhoneLoc) Find(ctx context.Context, in *PhoneLocReq) (*PhoneLocResp, error) {
	client := phoneloc.NewPhoneLocClient(m.cli.Conn())
	return client.Find(ctx, in)
}
