// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"context"
	"github.com/tal-tech/go-zero/core/service"
	"demo/app/mq/message/internal/logic"
	"demo/app/mq/message/internal/svc"
)

func RegisterDq(serverCtx *svc.ServiceContext, group *service.ServiceGroup) {
	//group.Add(logic.NewProducerLogic(context.Background(),serverCtx))
	group.Add(logic.NewConsumerLogic(context.Background(), serverCtx))
	group.Start()
}
